### ISSUE TITLE
Issue with dorking

### ISSUE THREAD

**Issue by Ekultek** [jesuiscamille/AutoSQLi#20]
```
[DEBUG] Loading save...
[DEBUG] current_save.stage in main(): 0
[DEBUG] Getting into the next stage
[DEBUG] Launching the dork stage
[DEBUG] interactively querying dork
[INFO] Enter a dork:
dork: "inurl:php?id=10"
 |__ dork: "inurl:php?id=10"
   |__ googly dorking...
[DEBUG] command: ['bash -c \' googler/googler -n 100 "inurl:php?id=10" --noprompt --json\'']; cwd: None; timeout: None; shellmode: True
bash: googler/googler: No such file or directory
Traceback (most recent call last):
  File "autosqli.py", line 46, in <module>
    main()
  File "autosqli.py", line 35, in main
    need_to_continue = stages.nextStage(args)
  File "/Users/admin/bin/tools/AutoSQLi/autosqli/stages.py", line 58, in nextStage
    launchDorkStage(args)
  File "/Users/admin/bin/tools/AutoSQLi/autosqli/stages.py", line 19, in launchDorkStage
    dork_stage(args)
  File "/Users/admin/bin/tools/AutoSQLi/autosqli/dork_stage.py", line 51, in dork_stage
    search_dork(dorks)
  File "/Users/admin/bin/tools/AutoSQLi/autosqli/dork_stage.py", line 12, in search_dork
    return find_dorks.dorkLines(dorks)
  File "/Users/admin/bin/tools/AutoSQLi/autosqli/find_dorks.py", line 55, in dorkLines
    result_clean = json.loads(result)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jesuiscamille** [comment]
It seems that bash didn't found googler... 
There are two possiblities:
     - AutoSQLi got launched in another directory ( at this moment, `$(pwd)` should be {...}/AutoSQLi )
     - Googler didn't got cloned ( AutoSQLi should be cloned using the `--recursive` switch

Anyway, there should be a way ( at least in the installer ) to check out that `googler` is there.
There also should be something in the code that would detect the directory in which autosqli.py is.

Thanks =)

**Comment by Ekultek** [comment]
it was probably the `--recursive` switch
