### ISSUE TITLE
ImportError: cannot import name save

### ISSUE THREAD

**Issue by Kalimon12** [jesuiscamille/AutoSQLi#21]
Traceback (most recent call last):
  File "autosqli.py", line 7, in <module>
    from autosqli import save
  File "/root/AutoSQLi/autosqli/save.py", line 3, in <module>
    from autosqli import stages
  File "/root/AutoSQLi/autosqli/stages.py", line 4, in <module>
    from autosqli import save
ImportError: cannot import name save

**Comment by jesuiscamille** [comment]
Hello @Kalimon12, and thanks for this report. 
To fix this, try to launch autosqli in it's clone directory.

**Comment by moorer2k** [comment]
I had this issue too, but then I noticed I was using python 2 for everything and the install had went ahead and used my normal pip installation (not pip3), so I went ahead and executed the following manually:

pip3 install -r requirements.txt

No errors, moved onto then launched with:

python3 autosqli.py 

and it started working fine.
